[package]
name = 'benchmarkStringDetection'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'benchmarkStringDetection'

[dependencies]
extendr-api = '*'
rayon = "1.10.0"
regex = "1.10.4"
